[[redirects]]
from = "/blogs"
to = "/maintenance"
status = 301

[[redirects]]
from = "/breaking-down-our-future-projects"
to = "/maintenance"
status = 301

[[redirects]]
from = "/*"
to = "/404/404.html"
status = 404

[[redirects]]
from = "/*"
to = "./403/403.html"
status = 403